apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce
data:
  # Service URLs for HTTP communication
  USER_SERVICE_URL: "http://user-service:8001"
  PRODUCT_SERVICE_URL: "http://product-service:8001"
  ORDER_SERVICE_URL: "http://order-service:8003"
  PAYMENT_SERVICE_URL: "http://payment-service:8004"
  # DynamoDB Tables
  ORDERS_TABLE: "ecommerce-orders"
  PAYMENTS_TABLE: "ecommerce-payments"
  # AWS Region
  AWS_REGION: "ap-south-1"
  # Kafka (AWS MSK)
  KAFKA_BOOTSTRAP_SERVERS: "b-1.ecommercekafka.uvcr6t.c2.kafka.ap-south-1.amazonaws.com:9092,b-2.ecommercekafka.uvcr6t.c2.kafka.ap-south-1.amazonaws.com:9092,b-3.ecommercekafka.uvcr6t.c2.kafka.ap-south-1.amazonaws.com:9092"
  KAFKA_ORDERS_TOPIC: "orders"
  KAFKA_RESULTS_TOPIC: "analytics-results"
  # General
  LOG_LEVEL: "info"
  ENVIRONMENT: "dev"
  METRICS_ENABLED: "true"
