apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce
data:
  # Service URLs for HTTP communication
  USER_SERVICE_URL: "http://user-service:8001"
  PRODUCT_SERVICE_URL: "http://product-service:8001"
  ORDER_SERVICE_URL: "http://order-service:8003"
  PAYMENT_SERVICE_URL: "http://payment-service:8004"
  # DynamoDB Tables
  ORDERS_TABLE: "ecommerce-orders"
  PAYMENTS_TABLE: "ecommerce-payments"
  # AWS Region
  AWS_REGION: "ap-south-1"
  # Kafka (Confluent Cloud)
  KAFKA_BOOTSTRAP_SERVERS: "pkc-41p56.asia-south1.gcp.confluent.cloud:9092"
  KAFKA_ORDERS_TOPIC: "orders"
  KAFKA_RESULTS_TOPIC: "analytics-results"
  KAFKA_SECURITY_PROTOCOL: "SASL_SSL"
  KAFKA_SASL_MECHANISM: "PLAIN"
  KAFKA_API_KEY: "I3XN2DJTHYXGK2EN"
  # API Secret stored in Kubernetes Secret, not in ConfigMap
  # SQS Queue for Lambda notifications
  SQS_QUEUE_URL: "https://sqs.ap-south-1.amazonaws.com/767828743009/ecommerce-order-events-dev"
  # General
  LOG_LEVEL: "info"
  ENVIRONMENT: "dev"
  METRICS_ENABLED: "true"
