apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - user-service-deployment.yaml
  - api-gateway-deployment.yaml
  - product-service-deployment.yaml
  - order-service-deployment.yaml
  - payment-service-deployment.yaml

commonLabels:
  app.kubernetes.io/part-of: ecommerce-platform
  managed-by: argocd

replicas:
  - name: user-service
    count: 2
  - name: api-gateway
    count: 2
  - name: product-service
    count: 2
